### ISSUE TITLE
use `parallelism` in `h2o.grid()`

### ISSUE THREAD

**Issue by qiushiyan** [tidymodels/agua#29]
We need to find a way to to specify `parallelism` in `h2o.grid()` and allow parallel model building. One possible solution is using `control_grid(parallel_over)` and have a condition for that [here](https://github.com/tidymodels/tune/blob/main/R/grid_code_paths.R#L113).

@topepo

**Comment by topepo** [comment]
`h2o.grid()` defaults `parallelism` to 1 (= sequential building). We should find a way to pass an option to `h2o.grid()`. 

The most direct route is to add an option to the control functions (e.g. `tune::control_grid()`, `finetune::tune_race_anova()`, etc) but this would be a big change for a single engine.

**Comment by topepo** [comment]
I think we can only do this as an option to the model or tuning functions. 

It makes sense to do it as a tuning option but it's not great to make another control option that only affects one engine (but affects multiple models). 

My initial thought is to add an option to our control functions that is `h2o_grid_options = list(parallelism = 0)` and that inject those options to `h2o::h2o.grid()`. There are very few (but not zero) options that folks might want to also specify. 

This would need to be added to pretty much all control functions for tuning (in tune and finetune).

Any thoughts on this design proposal?

**Comment by DavisVaughan** [comment]
A few other thoughts, in no particular order of goodness:

1. Can `set_engine()` take these details? like `%>% set_engine("h2o", parallelism = 0)`? My gut reaction is probably not, because these aren't parsnip related arguments, they are tune related arguments (I think?). Like, they effect the overarching tuning process not the individual model fit

2. Maybe you could have `agua::control_grid_h2o()` which would have those extra arguments in it? That way you can document them and check them for correctness. I guess you'd need h2o variants of the other `control_*()` functions too.

3. If you go the route of adding an argument directly to `tune::control_grid()`, you might want to consider something a little more generic than `h2o_grid_options`. These are arguments to the "tuning backend" so you might call it `backend_options` or something. It would be allowed to be a named list with no checks on the names or values. The "backend" would just attempt to pluck off elements that it knows how to recognize (with a fallback default), like `parallelism  <- backend_options$parallelism %||% 1L`. The typical tune path wouldn't use this argument at all, but the h2o path would, and if we ever added another "backend" in the future (unlikely but possible) then it would also use this argument. Somewhere in agua we'd document what options can be set as `backend_options`

**Comment by simonpcouch** [comment]
My inclination is that I'm missing something here, but---can we use foreach's machinery to detect the number of cores and pass that to `parallelism`? i.e. in

https://github.com/tidymodels/agua/blob/d6c8a31c5e20491a2757f44f69d413a84336ce60/R/tune.R#L134-L140

pass `parallelism = get_n_cores(control$allow_par)`, where

```
get_n_cores <- function(allow_par) {
  if (allow_par) {
       return(foreach::getDoParWorkers())
  }

  1
}

```

From my understanding, this would handle parallelism in a similar way to tune otherwise, where we just look to the existing parallelism setup. The user can adjust their foreach setup if they'd like to adjust `parallelism`, and there's no feature creep to tune itself.

Max's `h2o_grid_options` or Davis' `2.` or `3.` look fine to me, too.

**Comment by topepo** [comment]
@DavisVaughan 

For 1, the options gets passed to `h2o::h2o.grid()`, not the modeling functions (eg `h2o::h2o.glm()`). We can do some special things with the engine arguments to make that work, but it's probably less elegant than a tuning option. 

For 2, where would we pass that it? As an engine argument? We can do that but it ends up with more special code like my comment about point 1

For 3, that makes a lot of sense. 

@simonpcouch 

We can do parallelism at the same time using foreach and the h2o server. Weirdly, my initial testing has the best speedup when both are used ¯\_(ツ)_/¯ More testing/benchmarking will follow.

**Comment by DavisVaughan** [comment]
For 2, users would just replace `tune::control_grid()` with `agua::control_grid_h2o()`. Like `tune_grid(control = agua::control_grid_h2o())`.

`agua::control_grid_h2o()` would have all the same options as `control_grid()` + the special ones needed for h2o

**Comment by qiushiyan** [comment]
Davis' `2` and `3` looks good to me. 2 is easy to have with no impact on other packages if later h2o adds more options. 3 can be user-friendly without a special case function.

`parallelism` and `foreach` controls parallelization on the h2o server and R respectively, so I am leaning toward having them controlled in separate places and not have settings in one affect the other.
